######################################################################
# Automatically generated by qmake (2.01a) Fri Feb 11 11:20:00 2011
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += viewportal.h \
    phantomwindow.h
SOURCES += project.cpp viewportal.cpp \
    phantomwindow.cpp
